
export default {
    REGISTER: "REGISTER",
    LOGIN: 'LOGIN',

    CREATE_CV:'CREATE_CV',
    CREATE_JOB:'CREATE_JOB',
    USER_LOGIN :'USER_LOGIN',
    CURRENT_PAGE :'CURRENT_PAGE',
    CURRENT_USER :'CURRENT_USER',
    USER_LOGOUT : 'USER_LOGOUT'





}